Adding unit tests for org.atmosphere.util.uri.UriComponentTest
Diffblue-benchmarks/Atmosphere-atmosphere pull request #1
Opened 2019-08-29 08:12 UTC by EdgarScott

I've analysed your codebase and noticed that `org.atmosphere.util.uri.UriComponent is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look further.

2019-08-29 08:37 UTC, paulkennethkent requested changes
Out of interest there are a lot of inaccessible methods requiring reflection but there must be some kind of public interface where you can construct and access these methods, maybe this is a good case study.

2019-08-29 08:37 UTC, paulkennethkent commented on modules/runtime/src/test/java/org/atmosphere/uri/UriComponentTest.java
> +    public void constructorOutputVoid() throws InvocationTargetException,
I would remove the private constructor test

2019-09-03 08:05 UTC, paulkennethkent requested changes

2019-09-03 08:05 UTC, paulkennethkent commented on modules/runtime/src/test/java/org/atmosphere/uri/UriComponentTest.java
> +@RunWith(PowerMockRunner.class)
I don't believe there is any mocking here so you can remove this

2019-09-03 08:05 UTC, paulkennethkent commented on modules/runtime/src/test/java/org/atmosphere/uri/UriComponentTest.java
> +import org.powermock.modules.junit4.PowerMockRunner;
Remove this import

2019-09-03 08:05 UTC, paulkennethkent commented on modules/runtime/pom.xml
> +            <version>1.6.5</version>
After modifying the changes below you can remove this

2019-09-03 08:05 UTC, paulkennethkent commented on modules/runtime/pom.xml
> +            <version>1.6.5</version>
And the other powermock and mockito dependency

2019-09-16 07:46 UTC, EdgarScott commented
> Out of interest there are a lot of inaccessible methods requiring reflection but there must be some kind of public interface where you can construct and access these methods, maybe this is a good case study.

2019-09-17 08:23 UTC, paulkennethkent approved these changes

2019-09-17 09:46 UTC, closed without merging